project:
  type: website

website:
  title: "ISSS626"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
        - text: "Hands-on Exercise 1a"
          href: "Hands-on-Ex/Hands-on_Ex01/Hands-on_Ex01a.qmd"
        - text: "Hands-on Exercise 1b"
          href: "Hands-on-Ex/Hands-on_Ex01/Hands-on_Ex01b.qmd"
        - text: "Hands-on Exercise 2a"
          href: "Hands-on-Ex/Hands-on_Ex02/Hands-on_Ex02a.qmd"
        - text: "Hands-on Exercise 2b"
          href: "Hands-on-Ex/Hands-on_Ex02/Hands-on_Ex02b.qmd"
        
      - text: "In-class Exercise"
        menu: 
        - text: "In-class Exercise 1"
        - text: "In-class Exercise 2"     
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

