{
  "hash": "7f8192616463e16d80767c5456a82b9d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take Home Excercise 3\"\nauthor: \"Mohammad Farhan Ahsan\"\ndate: \"16/11/25\"\ndate-modified: \"last-modified\"\nformat: html\nexecute: \n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n  cache: false\n---\n\n## **Installing and Loading R packages**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(httr, tidyverse, sf, tmap, \n               jsonlite, progress, gtsummary, performance, RColorBrewer, sfdep, GWmodel)\n```\n:::\n\n\n## **Geocoding HDB resale data**\n\n### **Selecting data of interest**\n\nWe will filter out 3 room, 4 room and 5 room flats\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- read_csv(\n  \"data/rawdata/HDBresale.csv\") %>%\n  filter(flat_type == \"5 ROOM\") %>%\n  filter(month >= \"2025-01\" & month < \"2025-09\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale2 <- read_csv(\n  \"data/rawdata/HDBresale.csv\")\n```\n:::\n\n\nWe will create a function that helps us convert the address into latitude and longitude using OneMapSG api.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeocode <- function(block, streetname) {\n  base_url <- \"https://onemap.gov.sg/api/common/elastic/search\"\n  address <- paste(block, streetname, sep = \" \")\n  query <- list(\"searchVal\" = address, \n                \"returnGeom\" = \"Y\",\n                \"getAddrDetails\" = \"N\",\n                \"pageNum\" = \"1\")\n  \n  res <- GET(base_url, query = query)\n  restext<-content(res, as=\"text\")\n  \n  output <- fromJSON(restext)  %>% \n    as.data.frame %>%\n    select(results.LATITUDE, results.LONGITUDE)\n\n  return(output)\n}\n```\n:::\n\n\nNow we will use that function\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| code-summary: Get latitude and longitude of HDB flats\n#| output: false\n#| warning: false\n#| error: false\n#| message: false\n\nHDBresale$LATITUDE <- 0\nHDBresale$LONGITUDE <- 0\n\nfor (i in 1:nrow(HDBresale)){\n  temp_output <- geocode(HDBresale[i, 4], HDBresale[i, 5])\n  \n  HDBresale$LATITUDE[i] <- temp_output$results.LATITUDE\n  HDBresale$LONGITUDE[i] <- temp_output$results.LONGITUDE\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale %>% head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 13\n  month town  flat_type block street_name storey_range floor_area_sqm flat_model\n  <chr> <chr> <chr>     <chr> <chr>       <chr>                 <dbl> <chr>     \n1 2025… ANG … 5 ROOM    305   ANG MO KIO… 16 TO 18                123 Standard  \n2 2025… ANG … 5 ROOM    305   ANG MO KIO… 07 TO 09                123 Standard  \n3 2025… ANG … 5 ROOM    221   ANG MO KIO… 07 TO 09                126 Improved  \n4 2025… ANG … 5 ROOM    305   ANG MO KIO… 07 TO 09                123 Standard  \n5 2025… ANG … 5 ROOM    306   ANG MO KIO… 13 TO 15                123 Standard  \n6 2025… ANG … 5 ROOM    306   ANG MO KIO… 04 TO 06                123 Standard  \n# ℹ 5 more variables: lease_commence_date <dbl>, remaining_lease <chr>,\n#   resale_price <dbl>, LATITUDE <chr>, LONGITUDE <chr>\n```\n\n\n:::\n:::\n\n\nWe have the columns Latitude and Longitude.\n\n## **Proximity Analysis**\n\nCount number of geographic entities located within a defined distance of each HDB\n\nLet's count the number of preschools located within 350m of each resale HDB\n\nConvert hdb resale to sf\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale %>%\n  st_as_sf(\n    coords = c(\"LONGITUDE\", \"LATITUDE\"),\n    crs=4326) %>%\n  st_transform(crs = 3414)\n```\n:::\n\n\nImport preschool data\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool = st_read(\n  \"data/geospatial/PreSchoolsLocation.kml\") %>%\n  st_transform(crs= 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PRESCHOOLS_LOCATION' from data source \n  `C:\\farhanlion\\ISS626\\Take-Home-Ex\\Take-Home-Ex03\\data\\geospatial\\PreSchoolsLocation.kml' \n  using driver `KML'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nCHASclinic = st_read(\n  \"data/geospatial/CHASClinics.geojson\") %>%\n  st_transform(crs= 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CHASClinics' from data source \n  `C:\\farhanlion\\ISS626\\Take-Home-Ex\\Take-Home-Ex03\\data\\geospatial\\CHASClinics.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1193 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.5818 ymin: 1.016264 xmax: 103.9903 ymax: 1.456037\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nchildCareServices = st_read(\n  \"data/geospatial/ChildCareServices.geojson\") %>%\n  st_transform(crs= 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CHILDCARE' from data source \n  `C:\\farhanlion\\ISS626\\Take-Home-Ex\\Take-Home-Ex03\\data\\geospatial\\ChildCareServices.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1925 features and 16 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nhawkerCenters = st_read(\n  \"data/geospatial/HawkerCentres.geojson\") %>%\n  st_transform(crs= 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `SSOT_HAWKERCENTRES' from data source \n  `C:\\farhanlion\\ISS626\\Take-Home-Ex\\Take-Home-Ex03\\data\\geospatial\\HawkerCentres.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 129 features and 20 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6972 ymin: 1.272761 xmax: 103.9882 ymax: 1.448263\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nparks = st_read(\n  \"data/geospatial/Parks.geojson\") %>%\n  st_transform(crs= 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `NATIONALPARKS' from data source \n  `C:\\farhanlion\\ISS626\\Take-Home-Ex\\Take-Home-Ex03\\data\\geospatial\\Parks.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 450 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6929 ymin: 1.263958 xmax: 104.0538 ymax: 1.461944\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nsupermarkets = st_read(\n  \"data/geospatial/Supermarkets.geojson\") %>%\n  st_transform(crs= 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Supermarkets' from data source \n  `C:\\farhanlion\\ISS626\\Take-Home-Ex\\Take-Home-Ex03\\data\\geospatial\\Supermarkets.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 526 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6258 ymin: 1.24715 xmax: 104.0036 ymax: 1.461526\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\neldercare <- st_read(\n  dsn = \"data/geospatial\", \n  layer = \"ELDERCARE\"\n) %>% \n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ELDERCARE' from data source \n  `C:\\farhanlion\\ISS626\\Take-Home-Ex\\Take-Home-Ex03\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 133 features and 18 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 14481.92 ymin: 28218.43 xmax: 41665.14 ymax: 46804.9\nProjected CRS: SVY21\n```\n\n\n:::\n\n```{.r .cell-code}\ntrainstations = st_read(\n  \"data/geospatial/LTAMRTStationExitKML.kml\") %>%\n  st_transform(crs= 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MRT_EXITS' from data source \n  `C:\\farhanlion\\ISS626\\Take-Home-Ex\\Take-Home-Ex03\\data\\geospatial\\LTAMRTStationExitKML.kml' \n  using driver `KML'\nSimple feature collection with 563 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6368 ymin: 1.264972 xmax: 103.9893 ymax: 1.449157\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n### **Counting number of preschools**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithin_350m <- st_is_within_distance(\n  HDBresale_sf, preschool, dist = 350)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(WITHIN_350M_PRISCHOOL = map_int(within_350m, length))\n```\n:::\n\n\n### **Computing shortest distance**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnearest_dist <- function(from_geom, to_sf) {\n  as.numeric(\n    st_distance(\n      from_geom,\n      to_sf[st_nearest_feature(from_geom, to_sf), ],\n      by_element = TRUE\n    )\n  )\n}\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(\n    PROX_PRESCHOOL     = nearest_dist(geometry, preschool),\n    PROX_CHASCLINIC    = nearest_dist(geometry, CHASclinic),\n    PROX_CHILDCARE     = nearest_dist(geometry, childCareServices),\n    PROX_HAWKER        = nearest_dist(geometry, hawkerCenters),\n    PROX_PARK          = nearest_dist(geometry, parks),\n    PROX_SUPERMARKET   = nearest_dist(geometry, supermarkets),\n    PROX_ELDERCARE     = nearest_dist(geometry, eldercare),\n    PROX_TRAINSTATION  = nearest_dist(geometry, trainstations)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 4075 features and 20 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 11597.31 ymin: 28315.17 xmax: 42565.96 ymax: 48741.06\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 4,075 × 21\n   month   town       flat_type block street_name    storey_range floor_area_sqm\n * <chr>   <chr>      <chr>     <chr> <chr>          <chr>                 <dbl>\n 1 2025-03 ANG MO KIO 5 ROOM    305   ANG MO KIO AV… 16 TO 18                123\n 2 2025-04 ANG MO KIO 5 ROOM    305   ANG MO KIO AV… 07 TO 09                123\n 3 2025-05 ANG MO KIO 5 ROOM    221   ANG MO KIO AV… 07 TO 09                126\n 4 2025-06 ANG MO KIO 5 ROOM    305   ANG MO KIO AV… 07 TO 09                123\n 5 2025-07 ANG MO KIO 5 ROOM    306   ANG MO KIO AV… 13 TO 15                123\n 6 2025-08 ANG MO KIO 5 ROOM    306   ANG MO KIO AV… 04 TO 06                123\n 7 2025-01 ANG MO KIO 5 ROOM    458   ANG MO KIO AV… 13 TO 15                120\n 8 2025-02 ANG MO KIO 5 ROOM    460   ANG MO KIO AV… 01 TO 03                120\n 9 2025-02 ANG MO KIO 5 ROOM    437   ANG MO KIO AV… 01 TO 03                119\n10 2025-03 ANG MO KIO 5 ROOM    552   ANG MO KIO AV… 10 TO 12                119\n# ℹ 4,065 more rows\n# ℹ 14 more variables: flat_model <chr>, lease_commence_date <dbl>,\n#   remaining_lease <chr>, resale_price <dbl>, geometry <POINT [m]>,\n#   WITHIN_350M_PRISCHOOL <int>, PROX_PRESCHOOL <dbl>, PROX_CHASCLINIC <dbl>,\n#   PROX_CHILDCARE <dbl>, PROX_HAWKER <dbl>, PROX_PARK <dbl>,\n#   PROX_SUPERMARKET <dbl>, PROX_ELDERCARE <dbl>, PROX_TRAINSTATION <dbl>\n```\n\n\n:::\n:::\n\n\n## **1 Geospatial Data Wrangling**\n\n### **1.1 Importing geospatial data**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz = st_read(dsn = \"data/geospatial\", \n               layer = \"MP14_SUBZONE_WEB_PL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_WEB_PL' from data source \n  `C:\\farhanlion\\ISS626\\Take-Home-Ex\\Take-Home-Ex03\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n### **1.2 Updating CRS information**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_svy21 <- st_transform(mpsz, 3414)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(mpsz_svy21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\nEPSG: is indicated as *3414* now.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_bbox(mpsz_svy21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     xmin      ymin      xmax      ymax \n 2667.538 15748.721 56396.440 50256.334 \n```\n\n\n:::\n:::\n\n\nWe will calculate the Age of a flat\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stringr)\nlibrary(dplyr)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(\n    # Extract years and months  \n    lease_years  = as.numeric(str_extract(remaining_lease, \"\\\\d+(?= years?)\")),\n    lease_months = as.numeric(str_extract(remaining_lease, \"\\\\d+(?= months?)\")),\n    lease_months = ifelse(is.na(lease_months), 0, lease_months),\n    \n    # Convert to years\n    remaining_lease_num = lease_years + lease_months / 12,\n    \n    # Compute AGE\n    AGE = 99 - remaining_lease_num\n  )\n```\n:::\n\n\nWe will add a column called STOREY_MID to convert the floor to numeric\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(\n    storey_low  = as.numeric(str_extract(storey_range, \"^\\\\d+\")),\n    storey_high = as.numeric(str_extract(storey_range, \"\\\\d+$\")),\n    STOREY_MID  = (storey_low + storey_high) / 2\n  )\n```\n:::\n\n\n## **2 Exploratory Data Analysis (EDA)**\n\n### **2.1 EDA using statistical graphics**\n\nWe will plot a histogram of the resale price\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=HDBresale_sf, \n       aes(x=`resale_price`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nRight skewed meaning more hdb flats were transacted at lower relative prices.\n\nNormalize the resale price using a new variable called *log_resale_price* by using a log transformation on the variable resale_price It is performed using `mutate()` of **dplyr** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(`log_resale_price` = log(resale_price))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=HDBresale_sf, \n       aes(x=`log_resale_price`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\ndistribution is relatively less skewed after the transformation.\n\n### **2.2 Multiple Histogram Plots distribution of variables**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(purrr)\n\nvars <- c(\"PROX_PRESCHOOL\",\n          \"PROX_CHASCLINIC\",\n          \"PROX_CHILDCARE\",\n          \"PROX_HAWKER\",\n          \"PROX_PARK\",\n          \"PROX_SUPERMARKET\",\n          \"PROX_ELDERCARE\",\n          \"PROX_TRAINSTATION\")\nlibrary(ggplot2)\nlibrary(purrr)\nlibrary(ggpubr)\n\nplot_list <- map(vars, ~ {\n  ggplot(HDBresale_sf, aes(x = .data[[.x]])) +\n    geom_histogram(bins = 20, color = \"black\", fill = \"lightblue\") +\n    labs(title = .x, x = .x, y = \"Count\")\n})\n\nggarrange(plotlist = plot_list, \n          ncol = 3, \n          nrow = 3)\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nThe histograms reveal a consistent **right-skewed distribution** across all proximity variables. This is typical for distance-based features in Singapore’s dense urban environment, where many units are close to amenities while fewer units lie far away. Below is a variable-by-variable interpretation.\n\n### **2.3 Drawing Statistical Point Map**\n\nWe will plot the prices of HDB flats around singapore\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_svy21)+\n  tm_polygons() +\ntm_shape(HDBresale_sf) +  \n  tm_dots(fill = \"resale_price\",\n          fill_alpha = 0.6,\n          size = 0.5,\n          fill.scale = tm_scale_intervals(\n            style=\"quantile\")) +\n  tm_view(set_zoom_limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\nAs we can see flats in the central region and the eastcoast region tend to be more expensive. Flats in the north and west are much more affordable.\n\n### **2.4 Summary statistics of key variables**\n\nTo further explore the relationships between HDB resale prices and key structural and locational attributes, we generated a series of scatterplots comparing **log-transformed resale prices** against each predictor variable. Using `geom_point()` for individual transactions and `geom_smooth()` to fit a LOESS trend line, we visualised the potential functional form, monotonicity, and non-linearity between price and each independent variable. The variables examined included structural characteristics (floor area, flat age, and storey height) as well as proximity-based measures of accessibility and amenities (distance to MRT stations, hawker centres, parks, supermarkets, and eldercare facilities). These scatterplots provide an intuitive, visual first pass for assessing model suitability, identifying outliers, and detecting non-linear patterns prior to regression modelling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvars_for_scatter <- c(\n\"floor_area_sqm\", \"STOREY_MID\",\n\"PROX_TRAINSTATION\", \"PROX_HAWKER\",\n\"PROX_PARK\", \"PROX_SUPERMARKET\",\n\"PROX_ELDERCARE\", \"PROX_TRAINSTATION\"\n)\n\nplot_list2 <- map(vars_for_scatter, ~ {\nggplot(HDBresale_sf,\naes(x = .data[[.x]], y = log_resale_price)) +\ngeom_point(alpha = 0.3, size = 0.5) +\ngeom_smooth(se = FALSE) +\nlabs(title = paste(\"log(price) vs\", .x),\nx = .x, y = \"log(resale_price)\")\n})\n\nggpubr::ggarrange(plotlist = plot_list2,\nncol = 3, nrow = 3)\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nThe scatterplots reveal several important behavioural patterns. Floor area shows a strong positive association with resale price, though with diminishing marginal returns, while AGE displays a non-linear relationship—prices fall sharply as flats age but flatten out for very old units. Higher STOREY_MID levels correspond clearly to higher prices, reflecting the common preference for high-floor units. Most proximity variables show a **negative slope**: prices tend to be higher when flats are **closer** to amenities such as MRT stations, hawker centres, parks, supermarkets, and eldercare facilities. These relationships are generally smooth but exhibit varying degrees of curvature, suggesting that linear OLS models may not fully capture spatially varying effects. Combined, the patterns support the use of a hedonic pricing model and, given visible non-linearity and spatial clustering, motivate the need for geographically weighted modelling to better account for local variation in price drivers.\n\n#### 2.4.2 Spatial Variation in HDB Resale Prices Across Planning Areas\n\nWe spatially joined each HDB resale transaction to Singapore’s planning areas using `st_join()` with point-in-polygon matching based on the Master Plan subzone boundaries. Planning area names were added to each transaction, and areas with fewer than 20 sales were excluded to ensure reliable comparisons. A horizontal boxplot was then constructed to visualise the distribution of *log-transformed* resale prices within each planning area. The boxplots summarise the central tendency, dispersion, and extreme values of local resale markets, providing a clear visual profile of how pricing varies across the island.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf_pa <- st_join(\nHDBresale_sf,\nmpsz_svy21 %>% select(SUBZONE_N, PLN_AREA_N),\njoin = st_within,\nleft = TRUE\n)\n\nHDBresale_sf_pa %>%\nst_drop_geometry() %>%\ncount(PLN_AREA_N, sort = TRUE) %>%\nhead()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  PLN_AREA_N        n\n  <chr>         <int>\n1 SENGKANG        452\n2 TAMPINES        366\n3 WOODLANDS       364\n4 JURONG WEST     331\n5 PUNGGOL         317\n6 CHOA CHU KANG   264\n```\n\n\n:::\n\n```{.r .cell-code}\nHDBresale_sf_pa %>%\nst_drop_geometry() %>%\nfilter(!is.na(PLN_AREA_N)) %>%\ngroup_by(PLN_AREA_N) %>%\nfilter(n() >= 20) %>%    # keep only areas with at least 20 sales\nungroup() %>%\nggplot(aes(x = reorder(PLN_AREA_N, log_resale_price, median),\ny = log_resale_price)) +\ngeom_boxplot(outlier.alpha = 0.3) +\ncoord_flip() +\nlabs(x = \"Planning Area\",\ny = \"log(resale_price)\",\ntitle = \"Distribution of log(HDB resale prices) by Planning Area\")\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nThe boxplot reveals strong spatial heterogeneity in resale prices. Mature, centrally located areas such as **Queenstown, Bukit Merah, Toa Payoh, Bishan, and Kallang** exhibit both higher median prices and more compact distributions, reflecting stable demand and consistent housing characteristics. In contrast, peripheral towns such as **Woodlands, Choa Chu Kang, Sembawang, and Jurong West** show lower medians and wider spreads, indicative of more varied housing stock and weaker price pressures. The distinct gap between central and suburban regions highlights the influence of location, accessibility, and neighbourhood maturity on resale prices, reinforcing the need for geographically weighted methods to model these spatially varying relationships.\n\n#### 2.4.3 Spatial Pattern of Mean HDB Resale Prices by Planning Area\n\nEach polygon represents a planning area, shaded by the *mean log(resale price)* of 5-room HDB transactions within that area. Transactions were first spatially joined to planning areas, then the mean price and mean log(price) were computed per area. These summary statistics were merged back to the planning area layer and mapped using a quantile-based “Blues” colour scale, so darker shades correspond to higher average resale prices and lighter shades to lower ones. Areas with no 5-room resale transactions in the study period are shown in grey as “Missing”.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute mean price per planning area\n\nprice_pa <- HDBresale_sf_pa %>%\nst_drop_geometry() %>%\nfilter(!is.na(PLN_AREA_N)) %>%\ngroup_by(PLN_AREA_N) %>%\nsummarise(\nmean_price = mean(resale_price, na.rm = TRUE),\nmean_log_price = mean(log_resale_price, na.rm = TRUE),\nn = n()\n)\n\n# Join back to planning area polygons\n\nmpsz_price <- mpsz_svy21 %>%\nleft_join(price_pa, by = c(\"PLN_AREA_N\"))\n\ntmap_mode(\"plot\")\n\ntm_shape(mpsz_price) +\ntm_polygons(\ncol = \"mean_log_price\",\nstyle = \"quantile\",\nn = 5,\npalette = \"Blues\",\ntitle = \"Mean log(price)\"\n) +\ntm_layout(\nmain.title = \"Mean HDB Resale Prices by Planning Area\",\nlegend.outside = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nThe map shows a clear **central-to-peripheral price gradient**. Planning areas in the central and city-fringe region—such as Queenstown, Bukit Merah, Kallang/Whampoa, Toa Payoh and Bishan—form a dark-blue core with the highest mean resale prices, reflecting strong accessibility, mature amenities and established demand. Surrounding towns in the east and north-east (e.g. Tampines, Pasir Ris, Sengkang, Punggol) exhibit intermediate values, while outer western and northern areas (e.g. Jurong West, Choa Chu Kang, Woodlands, Sembawang) are generally lighter, indicating lower average prices. This broad spatial pattern supports the hypothesis that **location at the planning-area scale is a major determinant of resale value**, and it motivates the use of geographically weighted models to capture finer local variations within and across these areas.\n\n#### 2.4.4 Spatial Distribution of Flat Age and MRT Accessibility\n\nTwo geospatial dot maps were created to examine the spatial variation of two key structural and locational predictors: **flat age (AGE)** and **distance to the nearest MRT station (PROX_TRAINSTATION)**. Each resale transaction is plotted as a point overlaid on the Master Plan planning area boundaries. Points are coloured using quantile-based palettes (“YlOrRd” for AGE and “GnBu” for MRT proximity) to emphasise relative differences across the island. The first map shows how the age of flats varies spatially, while the second illustrates how close units are to MRT stations. This side-by-side arrangement allows direct visual comparison of structural ageing patterns and transport accessibility across Singapore.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\nAGE_map <- tm_shape(mpsz_svy21) +\ntm_polygons(alpha = 0.1) +\ntm_shape(HDBresale_sf) +\ntm_dots(\ncol = \"AGE\",\npalette = \"YlOrRd\",\nstyle = \"quantile\",\nsize = 0.5,\ntitle = \"Age (years)\"\n) +\ntm_layout(main.title = \"Spatial Distribution of Flat Age\")\n\nMRTprox_map <- tm_shape(mpsz_svy21) +\ntm_polygons(alpha = 0.1) +\ntm_shape(HDBresale_sf) +\ntm_dots(\ncol = \"PROX_TRAINSTATION\",\npalette = \"GnBu\",\nstyle = \"quantile\",\nsize = 0.5,\ntitle = \"Distance to MRT (m)\"\n) +\ntm_layout(main.title = \"Distance to Nearest MRT Station\")\n\ntmap_arrange(AGE_map, MRTprox_map,\nncol = 2, asp = 1, sync = TRUE)\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nThe spatial distribution of flat age shows that **older HDB flats are heavily concentrated in the central and mature estates**, such as Queenstown, Bukit Merah, Toa Payoh, and Ang Mo Kio. These areas were developed earlier, so many units exceed 30–40 years in age. In contrast, **newer flats—generally under 15 years old—are clustered in newer towns** such as Punggol, Sengkang, and parts of Jurong and Tampines. This reflects Singapore’s phased town development and the decentralisation strategy in recent decades.\n\nThe MRT proximity map reveals a different spatial pattern. **Flats closer to MRT stations** (light green shades) are mostly found in the **central, north-east, and eastern regions**, where the rail network is densest. Areas with **greater distances to MRT stations** (darker blue) typically lie in the outskirts—such as parts of Woodlands, Choa Chu Kang, and northern Yishun—where station spacing is wider. Notably, even within the same town, accessibility varies, creating micro-pockets of highly accessible versus more isolated blocks.\n\nTaken together, these maps highlight two key insights:\n\n1.  **Age and accessibility vary independently across space.** Older flats are not necessarily further from MRT stations, and newer neighbourhoods may still have inconsistent rail coverage.\n\n2.  These spatial disparities likely contribute to **systematic variation in resale prices across different regions**, reinforcing the need for spatial controls when modelling housing values.\n\n#### 2.4.5 Effect of MRT Distance on HDB Resale Prices\n\nThe scatterplot visualises the relationship between **log(resale price)** and the **log of distance to the nearest MRT station**, with each point representing an HDB resale transaction. The fitted smooth curve highlights the overall trend across the data. By applying logarithmic transformations to both variables, the plot reduces skewness from long-distance outliers and clarifies any underlying non-linear patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale_sf %>%\nmutate(\nlog_PROX_TRAIN = log(PROX_TRAINSTATION + 1),\nlog_PROX_HAWKER = log(PROX_HAWKER + 1)\n)\n\nggplot(HDBresale_sf,\naes(x = log_PROX_TRAIN, y = log_resale_price)) +\ngeom_point(alpha = 0.3, size = 0.5) +\ngeom_smooth(se = FALSE) +\nlabs(\ntitle = \"log(price) vs log(distance to MRT)\",\nx = \"log(distance to MRT + 1)\",\ny = \"log(resale_price)\"\n)\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nInterestingly, the trend is **relatively flat**, suggesting that after log-transformation, **distance to MRT alone has only a weak marginal effect on resale prices**. The smoothed line dips slightly around log(distance) ≈ 6 (roughly 400–500 m), where prices appear marginally lower, but rises again at larger distances—indicating no consistent monotonic relationship. This pattern suggests that MRT proximity in isolation does not strongly predict price, likely because (i) many towns have multiple accessibility alternatives (e.g., buses), (ii) other factors such as flat age, floor area, and planning area dominate pricing, and (iii) distance effects may vary spatially (e.g., central vs. suburban contexts). This flat trend reinforces the need for **multivariate modelling and spatial controls** to properly capture MRT effects.\n\n## **3 Hedonic Pricing Modelling in R**\n\nbuilding hedonic pricing models for HDB units using lm() of R base\n\n### **3.1 Simple Linear Regression Method**\n\nFirst, we will build a simple linear regression model by using *resale_price* as the dependent variable and *floor_area_sqm* as the independent variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBslr <- lm(formula=resale_price ~ floor_area_sqm,\n             data = HDBresale_sf)\n```\n:::\n\n\n`lm()` returns an object of class “lm” or for multiple responses of class c(“mlm”, “lm”).\n\nThe functions `summary()` and `anova()` can be used to obtain and print a summary and analysis of variance table of the results. The generic accessor functions coefficients, effects, fitted.values and residuals extract various useful features of the value returned by `lm`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(HDBslr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = resale_price ~ floor_area_sqm, data = HDBresale_sf)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-334629 -115215  -43094   60214  882713 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    799589.3    43220.5  18.500   <2e-16 ***\nfloor_area_sqm   -191.9      366.6  -0.523    0.601    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 169800 on 4073 degrees of freedom\nMultiple R-squared:  6.728e-05,\tAdjusted R-squared:  -0.0001782 \nF-statistic: 0.274 on 1 and 4073 DF,  p-value: 0.6007\n```\n\n\n:::\n:::\n\n\nThe output report reveals that the SELLING_PRICE for 4 room flats cannot be explained by using the formula:\n\n```         \n      *y = 799589.3 - 191.9(x)*\n```\n\nThe R-squared of 0.2987 reveals that the simple regression model built is able to explain about 29% of the resale prices.\n\nSince **p \\> 0.05**, the effect of floor area is **not significant.** We **fail to reject** the null hypothesis that the slope is 0. There is **no evidence** that floor area alone predicts resale price in this dataset.\n\nThis is expected because resale price is influenced by **storey**, **location**, **flat type**, **remaining lease**, **age**, etc. Floor area alone is too weak when comparing all 4 room flats.\n\nModel fit\n\n-   R-squared: **0.000067**\n\n-    Adjusted R-squared: **≈ 0**\n\nThis means the model explains **only 0.0067%** of the variation in resale prices—essentially **zero**. It has no predictive power\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=HDBresale_sf,  \n       aes(x=`floor_area_sqm`, y=`resale_price`)) +\n  geom_point() +\n  geom_smooth(method = lm)\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nA non-significant slope with an R-squared near zero means **changes in floor area do not systematically affect resale prices** when considered alone.\n\nThe simple linear regression model\n\nresale price∼floor area\n\ndoes **not** significantly explain resale prices. The slope is not statistically different from zero, the R-squared is effectively zero, and the model fails the overall significance test. This shows floor area alone is **not sufficient** to explain resale prices in Singapore—other factors like flat age, location, storey height, and amenity proximity must be included.\n\n### **3.2 Multiple Linear Regression Method**\n\n#### 3.2.1 Visualising the relationships of the independent variables\n\nBefore building a muulti linear regression model, we need to plot a correlation matrix to ensure none of the x variables are highly correlated.\n\nCorrelation Matrix\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corrplot)\n\nnum_vars <- HDBresale_sf %>%\n  st_drop_geometry() %>%\n  select(\n    floor_area_sqm, AGE, STOREY_MID,\n    starts_with(\"PROX\"), \n    log_resale_price\n  )\n\ncorr_matrix <- cor(num_vars, use = \"complete.obs\")\n\ncorrplot(corr_matrix,diag = FALSE, \n         order = \"AOE\",\n         tl.pos = \"td\", \n         tl.cex = 0.5, \n         method = \"number\", \n         type = \"upper\")\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nProx preschoon and prox child care can be removed as they arerepeating and pracrically the same thing. Hence we will only keep prox preschool\n\n### **3.3 Building a hedonic pricing model using multiple linear regression method**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBmlr <- lm(\n  formula = resale_price ~ floor_area_sqm + AGE  + PROX_ELDERCARE +\n    PROX_HAWKER + PROX_PARK +\n    PROX_SUPERMARKET + \n    STOREY_MID + PROX_PRESCHOOL +\n    PROX_TRAINSTATION + PROX_CHASCLINIC,\n  data=HDBresale_sf)\nsummary(HDBmlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = resale_price ~ floor_area_sqm + AGE + PROX_ELDERCARE + \n    PROX_HAWKER + PROX_PARK + PROX_SUPERMARKET + STOREY_MID + \n    PROX_PRESCHOOL + PROX_TRAINSTATION + PROX_CHASCLINIC, data = HDBresale_sf)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-360506  -76771  -14726   53865  593226 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       254869.604  38907.055   6.551 6.44e-11 ***\nfloor_area_sqm      6743.323    344.393  19.580  < 2e-16 ***\nAGE                -5918.990    205.834 -28.756  < 2e-16 ***\nPROX_ELDERCARE       -62.251      3.041 -20.473  < 2e-16 ***\nPROX_HAWKER          -90.653      4.177 -21.700  < 2e-16 ***\nPROX_PARK            -83.300      4.958 -16.801  < 2e-16 ***\nPROX_SUPERMARKET     -22.873     12.082  -1.893 0.058400 .  \nSTOREY_MID         10257.015    333.258  30.778  < 2e-16 ***\nPROX_PRESCHOOL        83.193     28.804   2.888 0.003894 ** \nPROX_TRAINSTATION    -17.868      5.293  -3.376 0.000743 ***\nPROX_CHASCLINIC     -123.599     18.409  -6.714 2.16e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 124300 on 4064 degrees of freedom\nMultiple R-squared:  0.4652,\tAdjusted R-squared:  0.4639 \nF-statistic: 353.5 on 10 and 4064 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe model achieves an **R-squared of 0.465**, indicating that approximately **46.5% of the variation in resale prices** is explained by the included predictors. This is a substantial improvement over the earlier simple regression and is expected because housing prices are influenced by many spatial and structural factors simultaneously.\n\nThe **overall F-test is highly significant (p \\< 2.2e-16)**, meaning the model as a whole provides strong explanatory power beyond the intercept-only model.\n\nKey insight:\n\nFloor area was not significant in the simple regression because several important variables—such as flat age, storey level, and locational attributes—were omitted, causing omitted variable bias. Many of these factors are correlated with floor area (e.g., older flats tend to be larger but cheaper; central flats tend to be smaller but more expensive), which suppressed the apparent effect of size on resale price.\\\n\nAfter controlling for these confounders in the multiple regression, the true positive relationship between floor area and resale price becomes clear and highly significant.\n\n### **3.4 Revising the model**\n\nLet's remove PROX_SUPERMARKET (p = 0.058) \\> 0.05. since it is not statistically significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBmlr1 <- lm(\n  formula = resale_price ~ floor_area_sqm + AGE  + PROX_ELDERCARE +\n    PROX_HAWKER + PROX_PARK + \n    STOREY_MID + PROX_PRESCHOOL +\n    PROX_TRAINSTATION + PROX_CHASCLINIC,\n  data=HDBresale_sf)\nsummary(HDBmlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = resale_price ~ floor_area_sqm + AGE + PROX_ELDERCARE + \n    PROX_HAWKER + PROX_PARK + STOREY_MID + PROX_PRESCHOOL + PROX_TRAINSTATION + \n    PROX_CHASCLINIC, data = HDBresale_sf)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-356579  -76330  -14699   53368  597066 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       246663.259  38677.132   6.377 2.00e-10 ***\nfloor_area_sqm      6758.892    344.405  19.625  < 2e-16 ***\nAGE                -5865.911    203.981 -28.757  < 2e-16 ***\nPROX_ELDERCARE       -61.579      3.021 -20.385  < 2e-16 ***\nPROX_HAWKER          -89.670      4.146 -21.626  < 2e-16 ***\nPROX_PARK            -82.691      4.949 -16.708  < 2e-16 ***\nSTOREY_MID         10282.793    333.085  30.871  < 2e-16 ***\nPROX_PRESCHOOL        77.180     28.637   2.695  0.00707 ** \nPROX_TRAINSTATION    -19.226      5.246  -3.665  0.00025 ***\nPROX_CHASCLINIC     -137.332     16.925  -8.114 6.42e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 124400 on 4065 degrees of freedom\nMultiple R-squared:  0.4647,\tAdjusted R-squared:  0.4636 \nF-statistic: 392.2 on 9 and 4065 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAfter removing the statistically insignificant predictor PROX_SUPERMARKET, the updated model continues to perform strongly, with an R² = 0.4647 and Adjusted R² = 0.4636. This means the refined model explains 46.4% of the variation in resale prices — almost identical to the earlier model — confirming that PROX_SUPERMARKET contributed little explanatory power.\n\nThe overall F-test remains highly significant (p \\< 2.2e-16), indicating the model as a whole reliably explains resale prices.\n\n### **3.5 Preparing Publication Quality Table: gtsummary method**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(HDBmlr1, intercept = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"butkwlbcct\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#butkwlbcct table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#butkwlbcct thead, #butkwlbcct tbody, #butkwlbcct tfoot, #butkwlbcct tr, #butkwlbcct td, #butkwlbcct th {\n  border-style: none;\n}\n\n#butkwlbcct p {\n  margin: 0;\n  padding: 0;\n}\n\n#butkwlbcct .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#butkwlbcct .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#butkwlbcct .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#butkwlbcct .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#butkwlbcct .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#butkwlbcct .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#butkwlbcct .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#butkwlbcct .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#butkwlbcct .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#butkwlbcct .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#butkwlbcct .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#butkwlbcct .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#butkwlbcct .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#butkwlbcct .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#butkwlbcct .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#butkwlbcct .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#butkwlbcct .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#butkwlbcct .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#butkwlbcct .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#butkwlbcct .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#butkwlbcct .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#butkwlbcct .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#butkwlbcct .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#butkwlbcct .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#butkwlbcct .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#butkwlbcct .gt_left {\n  text-align: left;\n}\n\n#butkwlbcct .gt_center {\n  text-align: center;\n}\n\n#butkwlbcct .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#butkwlbcct .gt_font_normal {\n  font-weight: normal;\n}\n\n#butkwlbcct .gt_font_bold {\n  font-weight: bold;\n}\n\n#butkwlbcct .gt_font_italic {\n  font-style: italic;\n}\n\n#butkwlbcct .gt_super {\n  font-size: 65%;\n}\n\n#butkwlbcct .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#butkwlbcct .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#butkwlbcct .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#butkwlbcct .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#butkwlbcct .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#butkwlbcct .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#butkwlbcct .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#butkwlbcct .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#butkwlbcct div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">246,663</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">170,835, 322,492</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">floor_area_sqm</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">6,759</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">6,084, 7,434</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AGE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-5,866</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-6,266, -5,466</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_ELDERCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-62</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-68, -56</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_HAWKER</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-90</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-98, -82</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PARK</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-83</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-92, -73</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">STOREY_MID</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">10,283</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">9,630, 10,936</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PRESCHOOL</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">77</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">21, 133</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.007</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_TRAINSTATION</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-19</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-30, -8.9</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CHASCLINIC</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-137</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-171, -104</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(HDBmlr1, \n               intercept = TRUE) %>% \n  add_glance_source_note(\n    label = list(sigma ~ \"\\U03C3\"),\n    include = c(r.squared, adj.r.squared, \n                AIC, statistic,\n                p.value, sigma))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dgwkcqkyjn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dgwkcqkyjn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dgwkcqkyjn thead, #dgwkcqkyjn tbody, #dgwkcqkyjn tfoot, #dgwkcqkyjn tr, #dgwkcqkyjn td, #dgwkcqkyjn th {\n  border-style: none;\n}\n\n#dgwkcqkyjn p {\n  margin: 0;\n  padding: 0;\n}\n\n#dgwkcqkyjn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dgwkcqkyjn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dgwkcqkyjn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dgwkcqkyjn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dgwkcqkyjn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dgwkcqkyjn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dgwkcqkyjn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dgwkcqkyjn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dgwkcqkyjn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dgwkcqkyjn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dgwkcqkyjn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dgwkcqkyjn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dgwkcqkyjn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dgwkcqkyjn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dgwkcqkyjn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dgwkcqkyjn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dgwkcqkyjn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dgwkcqkyjn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dgwkcqkyjn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dgwkcqkyjn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dgwkcqkyjn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dgwkcqkyjn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dgwkcqkyjn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dgwkcqkyjn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dgwkcqkyjn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dgwkcqkyjn .gt_left {\n  text-align: left;\n}\n\n#dgwkcqkyjn .gt_center {\n  text-align: center;\n}\n\n#dgwkcqkyjn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dgwkcqkyjn .gt_font_normal {\n  font-weight: normal;\n}\n\n#dgwkcqkyjn .gt_font_bold {\n  font-weight: bold;\n}\n\n#dgwkcqkyjn .gt_font_italic {\n  font-style: italic;\n}\n\n#dgwkcqkyjn .gt_super {\n  font-size: 65%;\n}\n\n#dgwkcqkyjn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dgwkcqkyjn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dgwkcqkyjn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dgwkcqkyjn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dgwkcqkyjn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dgwkcqkyjn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dgwkcqkyjn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dgwkcqkyjn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dgwkcqkyjn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">246,663</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">170,835, 322,492</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">floor_area_sqm</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">6,759</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">6,084, 7,434</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AGE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-5,866</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-6,266, -5,466</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_ELDERCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-62</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-68, -56</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_HAWKER</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-90</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-98, -82</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PARK</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-83</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-92, -73</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">STOREY_MID</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">10,283</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">9,630, 10,936</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PRESCHOOL</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">77</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">21, 133</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.007</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_TRAINSTATION</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-19</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-30, -8.9</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CHASCLINIC</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-137</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-171, -104</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"UsKyID0gMC40NjU7IEFkanVzdGVkIFLCsiA9IDAuNDY0OyBBSUMgPSAxMDcsMTg1OyBTdGF0aXN0aWMgPSAzOTI7IHAtdmFsdWUgPSA8MC4wMDE7IM+DID0gMTI0LDM4Ng==\"><span class='gt_from_md'>R² = 0.465; Adjusted R² = 0.464; AIC = 107,185; Statistic = 392; p-value = &lt;0.001; σ = 124,386</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n### **3.6 Regression Diagnostics**\n\n#### 3.6.1 Multicollinearity test\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_collinearity(HDBmlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n              Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n    floor_area_sqm 1.65 [1.58, 1.72]     1.28      0.61     [0.58, 0.63]\n               AGE 1.68 [1.61, 1.76]     1.30      0.60     [0.57, 0.62]\n    PROX_ELDERCARE 1.08 [1.05, 1.13]     1.04      0.93     [0.89, 0.95]\n       PROX_HAWKER 1.07 [1.04, 1.11]     1.03      0.94     [0.90, 0.96]\n         PROX_PARK 1.06 [1.04, 1.11]     1.03      0.94     [0.90, 0.96]\n        STOREY_MID 1.08 [1.05, 1.12]     1.04      0.93     [0.89, 0.95]\n    PROX_PRESCHOOL 1.04 [1.02, 1.09]     1.02      0.96     [0.91, 0.98]\n PROX_TRAINSTATION 1.09 [1.06, 1.14]     1.05      0.92     [0.88, 0.94]\n   PROX_CHASCLINIC 1.06 [1.04, 1.11]     1.03      0.94     [0.90, 0.97]\n```\n\n\n:::\n:::\n\n\nThe model has no multicollinearity problems.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr.vif <- check_collinearity(HDBmlr1)\nplot(mlr.vif)\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\nSince the VIF of the independent variables are less than 10. We can safely conclude that there are no sign of multicollinearity among the independent variables.\n\n#### 3.6.2 Test for Non-Linearity\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(HDBmlr1,\n            check = \"linearity\")\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nThe figure above reveals that most of the data poitns are scattered around the 0 line, hence we can safely conclude that the relationships between the dependent variable and independent variables are linear.\n\n#### 3.6.3 Test for Normality Assumption\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_normality(HDBmlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Non-normality of residuals detected (p < .001).\n```\n\n\n:::\n:::\n\n\nResiduals Are Not Normally Distributed\n\nThe print above reveals that the p-value of the normality assumption test is less than alpha value of 0.05. Hence we reject the normality assumption at 95% confident level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(check_normality(HDBmlr1), \n     type = \"qq\")\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\nQ-Q plot above below shows that majority of the data points are felt along the zero line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(HDBmlr1,\n            check= \"normality\")\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\nThe figure reveals that the residual of the multiple linear regression model (i.e. HDBmlr1) is resemble normal distribution\n\n#### 3.6.4 Testing for Spatial Autocorrelation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr.output <- as.data.frame(HDBmlr1$residuals)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- cbind(HDBresale_sf, \n                        HDBmlr1$residuals) %>%\nrename(`MLR_RES` = `HDBmlr1.residuals`)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_svy21) +\n  tm_polygons(fill_alpha = 0.4) +\ntm_shape(HDBresale_sf) +  \n  tm_dots(\n    fill = \"MLR_RES\",\n    size = 0.7,\n    col = \"black\",\n    fill.scale = tm_scale(\n      n = 10,\n      values = rev(\n        brewer.pal(11, \"RdBu\")),\n      style = \"quantile\",\n      midpoint = NA),\n    fill.legend = tm_legend(title = \"Residuals\")\n  ) + \n  tm_title(\"LM Residuals (Quantile Classification)\") +\n  tm_layout(legend.outside = TRUE) +\n  tm_view(set_zoom_limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\nThe clear clustering of high and low residual values across neighbourhoods suggests **spatial autocorrelation**.\n\nTo prove that our observation is indeed true, Global Moran’s I test will be performed\n\nFirst, we will compute the distance-based weight matrix by using [`st_dist_band()`](https://sfdep.josiahparry.com/reference/st_dist_band) function of **sfdep**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale_sf %>% \n  mutate(\n    nb = st_dist_band(\n      st_geometry(geometry), \n                 upper = 1500),\n    wt = st_weights(\n      nb, style = \"W\"),\n    .before = 1) \n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nglobal_moran_perm(\n  HDBresale_sf$MLR_RES, \n  nb = HDBresale_sf$nb, \n  wt = HDBresale_sf$wt,\n  alternative = \"two.sided\", \n  nsim = 499)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 500 \n\nstatistic = 0.50654, observed rank = 500, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe Global Moran’s I test confirms that the residuals from the multiple linear regression model exhibit significant spatial autocorrelation (Moran’s I = 0.5065, p \\< 2.2e-16). This indicates that residuals are spatially clustered rather than randomly distributed. Therefore, the model violates the assumption of spatial independence, suggesting that important spatial processes remain unaccounted for. A more appropriate spatial regression model—such as a Geographically Weighted Regression (GWR)—should be considered.\n\n## **4 Building Hedonic Pricing Models using GWRmodel**\n\nWe are now going to use a geographically weighted regression model. Since our multi regression residuals showed that the was not capturing some important location dependent factors that influence housing prices.\n\n### **4.1 Building Fixed Bandwidth GWR Model**\n\n#### 4.1.1 Computing fixed bandwith\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.fixed <- bw.gwr(\n  formula = resale_price ~ floor_area_sqm + AGE + PROX_ELDERCARE + PROX_PRESCHOOL +\n    PROX_HAWKER + PROX_PARK +\n    PROX_SUPERMARKET + \n    STOREY_MID + PROX_CHASCLINIC + PROX_TRAINSTATION,\n  data=HDBresale_sf, \n  approach=\"CV\", \n  kernel=\"gaussian\", \n  adaptive=FALSE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTake a cup of tea and have a break, it will take a few minutes.\n          -----A kind suggestion from GWmodel development group\nFixed bandwidth: 19232.05 CV score: 5.895999e+13 \nFixed bandwidth: 11888.44 CV score: 5.316767e+13 \nFixed bandwidth: 7349.836 CV score: 4.191598e+13 \nFixed bandwidth: 4544.826 CV score: 2.849943e+13 \nFixed bandwidth: 2811.234 CV score: 1.784104e+13 \nFixed bandwidth: 1739.815 CV score: 1.216144e+13 \nFixed bandwidth: 1077.642 CV score: 9.258286e+12 \nFixed bandwidth: 668.3961 CV score: 7.401789e+12 \nFixed bandwidth: 415.4684 CV score: 7.627965e+12 \nFixed bandwidth: 824.714 CV score: 8.009869e+12 \nFixed bandwidth: 571.7863 CV score: 7.176018e+12 \nFixed bandwidth: 512.0782 CV score: 7.153906e+12 \nFixed bandwidth: 475.1765 CV score: 7.215871e+12 \nFixed bandwidth: 534.8847 CV score: 7.145969e+12 \nFixed bandwidth: 548.9798 CV score: 7.152093e+12 \nFixed bandwidth: 526.1734 CV score: 7.14624e+12 \nFixed bandwidth: 540.2685 CV score: 7.147403e+12 \nFixed bandwidth: 531.5572 CV score: 7.145683e+12 \nFixed bandwidth: 529.5008 CV score: 7.145745e+12 \nFixed bandwidth: 532.8282 CV score: 7.145737e+12 \nFixed bandwidth: 530.7717 CV score: 7.145685e+12 \nFixed bandwidth: 532.0427 CV score: 7.145695e+12 \nFixed bandwidth: 531.2572 CV score: 7.145681e+12 \nFixed bandwidth: 531.0718 CV score: 7.145681e+12 \nFixed bandwidth: 531.3718 CV score: 7.145681e+12 \nFixed bandwidth: 531.1864 CV score: 7.145681e+12 \nFixed bandwidth: 531.1426 CV score: 7.145681e+12 \nFixed bandwidth: 531.2134 CV score: 7.145681e+12 \nFixed bandwidth: 531.2301 CV score: 7.145681e+12 \nFixed bandwidth: 531.2031 CV score: 7.145681e+12 \nFixed bandwidth: 531.2198 CV score: 7.145681e+12 \nFixed bandwidth: 531.2238 CV score: 7.145681e+12 \nFixed bandwidth: 531.2174 CV score: 7.145681e+12 \nFixed bandwidth: 531.2213 CV score: 7.145681e+12 \nFixed bandwidth: 531.2189 CV score: 7.145681e+12 \nFixed bandwidth: 531.2204 CV score: 7.145681e+12 \nFixed bandwidth: 531.2195 CV score: 7.145681e+12 \nFixed bandwidth: 531.22 CV score: 7.145681e+12 \nFixed bandwidth: 531.2197 CV score: 7.145681e+12 \nFixed bandwidth: 531.2196 CV score: 7.145681e+12 \nFixed bandwidth: 531.2197 CV score: 7.145681e+12 \nFixed bandwidth: 531.2196 CV score: 7.145681e+12 \n```\n\n\n:::\n:::\n\n\nThe optimal fixed bandwidth for the GWR model was determined using cross-validation. During the search, *bw.gwr()* evaluated a wide range of candidate bandwidths, beginning with very large neighbourhood sizes (≈19 km) and systematically shrinking them while tracking changes in the CV score. The CV score decreased rapidly as the bandwidth narrowed, indicating that smaller neighbourhoods better capture local variation in HDB resale prices. The score eventually stabilised and reached its minimum at approximately **531 metres**, which the algorithm selected as the optimal fixed bandwidth.\n\nThis result implies that the relationship between housing attributes and resale prices varies meaningfully over relatively small spatial scales—roughly **a 500 m radius**, i.e., the scale of a typical HDB precinct. Observations within this distance exert the strongest influence on each local regression, while those farther away are down-weighted under the Gaussian kernel.\n\nSince our data is stored in a projected coordinate system, specifically EPSG 3414, the units are in meters.\n\n#### 4.1.2 GWModel method - fixed bandwith\n\nWe are now fitting the **Geographically Weighted Regression (GWR)** model using the optimal fixed bandwidth obtained earlier (\\~531 m). The function **`gwr.basic()`** calibrates a separate local regression equation for every HDB transaction point, allowing the coefficients to vary across space rather than assuming a single global relationship.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.fixed <- gwr.basic(\n  formula = resale_price ~ floor_area_sqm + AGE + PROX_ELDERCARE + PROX_PRESCHOOL +\n    PROX_HAWKER + PROX_PARK +\n    PROX_SUPERMARKET + \n    STOREY_MID + PROX_CHASCLINIC + PROX_TRAINSTATION,\n  data=HDBresale_sf, \n  bw=bw.fixed, \n  kernel = 'gaussian',\n  longlat = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.fixed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-11-17 15:27:05.412696 \n   Call:\n   gwr.basic(formula = resale_price ~ floor_area_sqm + AGE + PROX_ELDERCARE + \n    PROX_PRESCHOOL + PROX_HAWKER + PROX_PARK + PROX_SUPERMARKET + \n    STOREY_MID + PROX_CHASCLINIC + PROX_TRAINSTATION, data = HDBresale_sf, \n    bw = bw.fixed, kernel = \"gaussian\", longlat = FALSE)\n\n   Dependent (y) variable:  resale_price\n   Independent variables:  floor_area_sqm AGE PROX_ELDERCARE PROX_PRESCHOOL PROX_HAWKER PROX_PARK PROX_SUPERMARKET STOREY_MID PROX_CHASCLINIC PROX_TRAINSTATION\n   Number of data points: 4075\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n    Min      1Q  Median      3Q     Max \n-360506  -76771  -14726   53865  593226 \n\n   Coefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)       254869.604  38907.055   6.551 6.44e-11 ***\n   floor_area_sqm      6743.323    344.393  19.580  < 2e-16 ***\n   AGE                -5918.990    205.834 -28.756  < 2e-16 ***\n   PROX_ELDERCARE       -62.251      3.041 -20.473  < 2e-16 ***\n   PROX_PRESCHOOL        83.193     28.804   2.888 0.003894 ** \n   PROX_HAWKER          -90.653      4.177 -21.700  < 2e-16 ***\n   PROX_PARK            -83.300      4.958 -16.801  < 2e-16 ***\n   PROX_SUPERMARKET     -22.873     12.082  -1.893 0.058400 .  \n   STOREY_MID         10257.015    333.258  30.778  < 2e-16 ***\n   PROX_CHASCLINIC     -123.599     18.409  -6.714 2.16e-11 ***\n   PROX_TRAINSTATION    -17.868      5.293  -3.376 0.000743 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 124300 on 4064 degrees of freedom\n   Multiple R-squared: 0.4652\n   Adjusted R-squared: 0.4639 \n   F-statistic: 353.5 on 10 and 4064 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 6.283744e+13\n   Sigma(hat): 124208.7\n   AIC:  107183.6\n   AICc:  107183.6\n   BIC:  103284.1\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Fixed bandwidth: 531.2197 \n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                            Min.     1st Qu.      Median     3rd Qu.       Max.\n   Intercept         -5.1400e+06  2.0223e+05  3.9970e+05  6.7074e+05 1972653.54\n   floor_area_sqm    -6.2738e+03  2.4711e+03  4.2399e+03  6.9736e+03   16803.73\n   AGE               -2.8322e+04 -9.1182e+03 -6.7108e+03 -4.4630e+03   76238.85\n   PROX_ELDERCARE    -9.9255e+02 -3.5657e+01 -1.1544e+01  2.2184e+01     571.67\n   PROX_PRESCHOOL    -7.4495e+02 -5.3290e+01  1.9409e+01  7.9485e+01    1082.33\n   PROX_HAWKER       -8.6732e+02 -6.8034e+01 -2.4459e+01  1.6615e+01     613.27\n   PROX_PARK         -4.2463e+02 -3.0407e+01  5.0233e+00  3.2096e+01     993.83\n   PROX_SUPERMARKET  -1.3792e+03 -8.6931e+01 -1.6285e+01  3.1757e+01    1462.08\n   STOREY_MID         2.0357e+03  4.0931e+03  5.0491e+03  6.6215e+03   21989.49\n   PROX_CHASCLINIC   -1.4403e+03 -6.8323e+01  2.4464e+00  5.9010e+01     938.90\n   PROX_TRAINSTATION -8.5748e+02 -1.2785e+02 -8.4843e+01 -4.8991e+01    1273.63\n   ************************Diagnostic information*************************\n   Number of data points: 4075 \n   Effective number of parameters (2trace(S) - trace(S'S)): 830.7303 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 3244.27 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 97538.47 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 96587.61 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 97466.14 \n   Residual sum of squares: 3.974816e+12 \n   R-square value:  0.9661715 \n   Adjusted R-square value:  0.9575067 \n\n   ***********************************************************************\n   Program stops at: 2025-11-17 15:27:11.902328 \n```\n\n\n:::\n:::\n\n\nThe AICc of the GWR model (97,538.47) is substantially lower than that of the global multiple linear regression model (107,183.6). Because AICc penalizes model complexity, this reduction indicates a significantly better model fit even after accounting for GWR’s larger number of effective parameters. Combined with the sharp reduction in residual sum of squares and the increase in R² from 0.465 (MLR) to 0.966 (GWR), the results strongly suggest that spatially varying relationships are present. Therefore, GWR captures important local housing market dynamics that the global MLR model fails to detect.\\\n\n### **4.2 Building Adaptive Bandwidth GWR Model**\n\nBecause HDB resale transactions are not evenly distributed across Singapore, a fixed bandwidth is not suitable. In dense regions (e.g., Jurong, Tampines, Bukit Merah), a fixed distance would include too many neighbouring transactions, causing excessive smoothing. In contrast, sparse regions (e.g., Sembawang, Lim Chu Kang, Tengah) would include too few neighbours, leading to unstable and unreliable local regressions. Using an **adaptive bandwidth** ensures that each local model uses a consistent number of nearby observations, resulting in more stable and meaningful GWR estimates across varying spatial densities.\n\n#### 4.2.1 Computing the adaptive bandwidth\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.adaptive <- bw.gwr(\n  formula = resale_price ~ floor_area_sqm + AGE + PROX_ELDERCARE + PROX_PRESCHOOL +\n    PROX_HAWKER + PROX_PARK +\n    PROX_SUPERMARKET + \n    STOREY_MID + PROX_CHASCLINIC + PROX_TRAINSTATION,\n  data=HDBresale_sf,\n  approach=\"CV\", \n  kernel=\"gaussian\", \n  adaptive=TRUE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTake a cup of tea and have a break, it will take a few minutes.\n          -----A kind suggestion from GWmodel development group\nAdaptive bandwidth: 2526 CV score: 5.57787e+13 \nAdaptive bandwidth: 1569 CV score: 5.071643e+13 \nAdaptive bandwidth: 977 CV score: 4.2486e+13 \nAdaptive bandwidth: 611 CV score: 3.455521e+13 \nAdaptive bandwidth: 385 CV score: 2.742367e+13 \nAdaptive bandwidth: 245 CV score: 2.069189e+13 \nAdaptive bandwidth: 159 CV score: 1.56898e+13 \nAdaptive bandwidth: 105 CV score: 1.321309e+13 \nAdaptive bandwidth: 72 CV score: 1.127536e+13 \nAdaptive bandwidth: 51 CV score: 9.429486e+12 \nAdaptive bandwidth: 39 CV score: 8.533928e+12 \nAdaptive bandwidth: 30 CV score: 1.088895e+13 \nAdaptive bandwidth: 43 CV score: 8.829041e+12 \nAdaptive bandwidth: 35 CV score: 8.208705e+12 \nAdaptive bandwidth: 34 CV score: 8.144997e+12 \nAdaptive bandwidth: 32 CV score: 1.100768e+13 \nAdaptive bandwidth: 34 CV score: 8.144997e+12 \n```\n\n\n:::\n:::\n\n\nThe cross-validation procedure identified an adaptive bandwidth of 34 nearest neighbours, which minimizes the prediction error. This indicates that the housing price relationships are highly localised, with each location requiring only a small subset of nearby observations to model the spatially varying effects effectively.\n\n#### 4.2.2 Constructing the adaptive bandwidth gwr model\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive <- gwr.basic(\n  formula = resale_price ~ floor_area_sqm + AGE + PROX_ELDERCARE + PROX_PRESCHOOL +\n    PROX_HAWKER + PROX_PARK +\n    PROX_SUPERMARKET + \n    STOREY_MID + PROX_CHASCLINIC + PROX_TRAINSTATION,\n  data=HDBresale_sf,\n  bw=bw.adaptive, \n  kernel = 'gaussian', \n  adaptive=TRUE, \n  longlat = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-11-17 15:28:01.676657 \n   Call:\n   gwr.basic(formula = resale_price ~ floor_area_sqm + AGE + PROX_ELDERCARE + \n    PROX_PRESCHOOL + PROX_HAWKER + PROX_PARK + PROX_SUPERMARKET + \n    STOREY_MID + PROX_CHASCLINIC + PROX_TRAINSTATION, data = HDBresale_sf, \n    bw = bw.adaptive, kernel = \"gaussian\", adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  resale_price\n   Independent variables:  floor_area_sqm AGE PROX_ELDERCARE PROX_PRESCHOOL PROX_HAWKER PROX_PARK PROX_SUPERMARKET STOREY_MID PROX_CHASCLINIC PROX_TRAINSTATION\n   Number of data points: 4075\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n    Min      1Q  Median      3Q     Max \n-360506  -76771  -14726   53865  593226 \n\n   Coefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)       254869.604  38907.055   6.551 6.44e-11 ***\n   floor_area_sqm      6743.323    344.393  19.580  < 2e-16 ***\n   AGE                -5918.990    205.834 -28.756  < 2e-16 ***\n   PROX_ELDERCARE       -62.251      3.041 -20.473  < 2e-16 ***\n   PROX_PRESCHOOL        83.193     28.804   2.888 0.003894 ** \n   PROX_HAWKER          -90.653      4.177 -21.700  < 2e-16 ***\n   PROX_PARK            -83.300      4.958 -16.801  < 2e-16 ***\n   PROX_SUPERMARKET     -22.873     12.082  -1.893 0.058400 .  \n   STOREY_MID         10257.015    333.258  30.778  < 2e-16 ***\n   PROX_CHASCLINIC     -123.599     18.409  -6.714 2.16e-11 ***\n   PROX_TRAINSTATION    -17.868      5.293  -3.376 0.000743 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 124300 on 4064 degrees of freedom\n   Multiple R-squared: 0.4652\n   Adjusted R-squared: 0.4639 \n   F-statistic: 353.5 on 10 and 4064 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 6.283744e+13\n   Sigma(hat): 124208.7\n   AIC:  107183.6\n   AICc:  107183.6\n   BIC:  103284.1\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 34 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                            Min.     1st Qu.      Median     3rd Qu.       Max.\n   Intercept         -1.6097e+06  2.3704e+05  4.4261e+05  6.9247e+05 5522251.31\n   floor_area_sqm    -1.8169e+04  2.4896e+03  4.3094e+03  6.9451e+03   15363.48\n   AGE               -1.6365e+04 -9.1935e+03 -6.4635e+03 -4.3711e+03   25906.94\n   PROX_ELDERCARE    -2.3294e+03 -4.3522e+01 -1.5006e+01  1.7075e+01    4919.62\n   PROX_PRESCHOOL    -4.8813e+02 -6.1668e+01  8.9637e+00  6.8707e+01    1455.48\n   PROX_HAWKER       -2.8707e+03 -5.7970e+01 -1.8881e+01  3.2845e+01    1795.99\n   PROX_PARK         -4.5796e+02 -3.8398e+01 -2.7799e-01  3.3973e+01    2435.70\n   PROX_SUPERMARKET  -6.8267e+02 -9.7709e+01 -1.9555e+01  4.8471e+01     410.57\n   STOREY_MID         2.3793e+03  4.2039e+03  5.2892e+03  6.7140e+03   11092.78\n   PROX_CHASCLINIC   -1.4512e+03 -7.2550e+01  2.3697e+00  5.8099e+01     594.45\n   PROX_TRAINSTATION -4.0643e+03 -1.3816e+02 -8.9035e+01 -4.6059e+01    2174.02\n   ************************Diagnostic information*************************\n   Number of data points: 4075 \n   Effective number of parameters (2trace(S) - trace(S'S)): 697.3645 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 3377.636 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 98816.61 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 98093.14 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 98034.88 \n   Residual sum of squares: 5.935007e+12 \n   R-square value:  0.9494889 \n   Adjusted R-square value:  0.939057 \n\n   ***********************************************************************\n   Program stops at: 2025-11-17 15:28:09.158268 \n```\n\n\n:::\n:::\n\n\nBoth fixed and adaptive GWR models were estimated to account for the spatial heterogeneity present in HDB resale prices. Although adaptive GWR is typically preferred for datasets with uneven spatial distributions—because it adjusts the bandwidth based on local data density—the results from our analysis indicate that the **fixed-bandwidth GWR performs better for this study**. The fixed model, calibrated using a constant spatial distance of approximately 531 metres, achieved a substantially **lower AICc (97,538.47)** and **smaller residual sum of squares (3.97 × 10¹²)** compared to the adaptive model (AICc = 98,816.61; RSS = 5.94 × 10¹²). It also recorded a **higher R² (0.966)**, indicating a stronger overall fit.\n\n### **4.3 Visualising GWR Output**\n\n### **4.4 Converting SDF into *sf* data.frame**\n\nWe take the GWR results (stored in `gwr.fixed$SDF`) and turn them into an `sf` object so we can map fields like `Local_R2`, `yhat`, coefficients, etc.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf.fixed <-\n  st_as_sf(gwr.fixed$SDF) %>%\n  st_transform(crs=3414)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(HDBresale_sf.fixed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 4,075\nColumns: 40\n$ Intercept            <dbl> 367564.5, 367564.5, 1007542.7, 367564.5, 422214.6…\n$ floor_area_sqm       <dbl> 5842.4737, 5842.4737, -407.7870, 5842.4737, 5202.…\n$ AGE                  <dbl> -11360.302, -11360.302, -8319.442, -11360.302, -1…\n$ PROX_ELDERCARE       <dbl> 80.112548, 80.112548, -25.213817, 80.112548, 76.7…\n$ PROX_PRESCHOOL       <dbl> 203.32605, 203.32605, 58.43097, 203.32605, 194.79…\n$ PROX_HAWKER          <dbl> 144.32712, 144.32712, 323.23166, 144.32712, 150.8…\n$ PROX_PARK            <dbl> 79.48426, 79.48426, -52.75669, 79.48426, 60.80662…\n$ PROX_SUPERMARKET     <dbl> -51.629104, -51.629104, 7.727087, -51.629104, -42…\n$ STOREY_MID           <dbl> 7076.195, 7076.195, 7287.682, 7076.195, 7180.694,…\n$ PROX_CHASCLINIC      <dbl> 123.94017, 123.94017, -72.28603, 123.94017, 131.4…\n$ PROX_TRAINSTATION    <dbl> 54.11863, 54.11863, 182.40709, 54.11863, 75.41720…\n$ y                    <dbl> 830000, 865000, 850000, 770000, 838000, 740000, 7…\n$ yhat                 <dbl> 836511.1, 771878.6, 856681.3, 769038.5, 827715.9,…\n$ residual             <dbl> -6511.0658, 93121.3841, -6681.3248, 961.4595, 102…\n$ CV_Score             <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ Stud_residual        <dbl> -0.20915516, 2.92093591, -0.39922525, 0.03016929,…\n$ Intercept_SE         <dbl> 107039.78, 107039.78, 99064.43, 107039.78, 106004…\n$ floor_area_sqm_SE    <dbl> 885.8994, 885.8994, 852.7301, 885.8994, 880.4558,…\n$ AGE_SE               <dbl> 496.4124, 496.4124, 617.7901, 496.4124, 506.9843,…\n$ PROX_ELDERCARE_SE    <dbl> 17.47160, 17.47160, 32.60056, 17.47160, 17.76743,…\n$ PROX_PRESCHOOL_SE    <dbl> 85.73308, 85.73308, 92.67182, 85.73308, 86.91325,…\n$ PROX_HAWKER_SE       <dbl> 26.97995, 26.97995, 31.14242, 26.97995, 26.49909,…\n$ PROX_PARK_SE         <dbl> 44.36804, 44.36804, 50.17622, 44.36804, 44.80072,…\n$ PROX_SUPERMARKET_SE  <dbl> 44.26201, 44.26201, 45.74341, 44.26201, 44.44490,…\n$ STOREY_MID_SE        <dbl> 746.0410, 746.0410, 737.2154, 746.0410, 756.4374,…\n$ PROX_CHASCLINIC_SE   <dbl> 91.38896, 91.38896, 76.44428, 91.38896, 88.63823,…\n$ PROX_TRAINSTATION_SE <dbl> 34.24107, 34.24107, 34.42501, 34.24107, 34.72923,…\n$ Intercept_TV         <dbl> 3.433905, 3.433905, 10.170580, 3.433905, 3.982984…\n$ floor_area_sqm_TV    <dbl> 6.5949628, 6.5949628, -0.4782134, 6.5949628, 5.90…\n$ AGE_TV               <dbl> -22.884805, -22.884805, -13.466455, -22.884805, -…\n$ PROX_ELDERCARE_TV    <dbl> 4.5853000, 4.5853000, -0.7734167, 4.5853000, 4.31…\n$ PROX_PRESCHOOL_TV    <dbl> 2.3716174, 2.3716174, 0.6305149, 2.3716174, 2.241…\n$ PROX_HAWKER_TV       <dbl> 5.3494222, 5.3494222, 10.3791431, 5.3494222, 5.69…\n$ PROX_PARK_TV         <dbl> 1.7914753, 1.7914753, -1.0514282, 1.7914753, 1.35…\n$ PROX_SUPERMARKET_TV  <dbl> -1.16644277, -1.16644277, 0.16892239, -1.16644277…\n$ STOREY_MID_TV        <dbl> 9.484996, 9.484996, 9.885418, 9.484996, 9.492780,…\n$ PROX_CHASCLINIC_TV   <dbl> 1.3561832, 1.3561832, -0.9456042, 1.3561832, 1.48…\n$ PROX_TRAINSTATION_TV <dbl> 1.580518, 1.580518, 5.298679, 1.580518, 2.171577,…\n$ Local_R2             <dbl> 0.9559164, 0.9559164, 0.9635649, 0.9559164, 0.955…\n$ geometry             <POINT [m]> POINT (29412.84 38680.21), POINT (29412.84 …\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(gwr.fixed$SDF$yhat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 468065  665552  734187  776999  834364 1625394 \n```\n\n\n:::\n:::\n\n\nPredicted resale prices range from **≈ \\$468k to \\$1.63M**, with a median around **\\$734k**, which looks realistic for 5-room HDBs.\n\n### **4.5 Visualising local R2**\n\nWe plot each transaction coloured by its **local R²** from the fixed-bandwidth GWR.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(mpsz_svy21)+\n  tm_polygons(fill_alpha = 0.1) +\ntm_shape(HDBresale_sf.fixed) +  \n  tm_dots(col = \"Local_R2\",\n          border.col = \"gray60\",\n          border.lwd = 1) +\n  tm_view(set.zoom.limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-60-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\nThe Local R² map shows that the fixed GWR model achieves very high explanatory power across most of Singapore, with many neighbourhoods exhibiting Local R² values above 0.9. Areas with slightly lower Local R² highlight pockets where additional local factors—beyond the included structural and proximity variables—may be influencing HDB resale prices.\n\n### **4.6 Visualising coefficient estimates**\n\nWe will visualize all the coefficients estimates\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\n# 1. Get base map\nbase_map <- tm_shape(mpsz_svy21) + tm_polygons(alpha = 0.1)\n\n# 2. Identify all SE fields\nse_vars <- grep(\"_SE$\", names(HDBresale_sf.fixed), value = TRUE)\n\n# 3. Loop and produce arranged maps\nplot_list <- lapply(se_vars, function(se_var) {\n  \n  # matching TV variable\n  tv_var <- sub(\"_SE$\", \"_TV\", se_var)\n  \n  # pretty title\n  var_name <- sub(\"_SE$\", \"\", se_var)\n  \n  # SE map\n  map_se <- base_map +\n    tm_shape(HDBresale_sf.fixed) +\n    tm_dots(col = se_var,\n            border.col = \"gray60\",\n            border.lwd = 1) +\n    tm_layout(title = paste0(var_name, \" (Std. Error)\"))\n  \n  # TV map\n  map_tv <- base_map +\n    tm_shape(HDBresale_sf.fixed) +\n    tm_dots(col = tv_var,\n            border.col = \"gray60\",\n            border.lwd = 1) +\n    tm_layout(title = paste0(var_name, \" (t-value)\"))\n  \n  # Arrange side-by-side\n  tmap_arrange(map_se, map_tv, asp = 1, ncol = 2, sync = TRUE)\n})\n\n# 4. Display all maps\nplot_list\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[3]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-3.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[4]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-4.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[5]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-5.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[6]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-6.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[7]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-7.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[8]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-8.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[9]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-9.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[10]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-10.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[11]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](TakeHome_Ex03_files/figure-html/unnamed-chunk-61-11.png){width=672}\n:::\n:::\n\n\n**Floor Area (floor_area_sqm)**\n\nFloor area has consistently low standard errors in dense, mature estates, indicating highly stable coefficient estimates. Its t-values are strongly positive across most of Singapore, confirming that floor size is a universally significant driver of resale price.\n\n**Age of Flat (AGE)**\n\nAGE shows low standard errors in central and established towns, suggesting reliable estimation. The t-values are strongly negative almost everywhere, indicating that older flats systematically command lower resale prices.\n\n**Proximity to Eldercare (PROX_ELDERCARE)**\n\nStandard errors are higher in peripheral or newly developed towns, showing instability in sparse areas. T-values are generally weak or inconsistent, implying that eldercare proximity has little or highly localised influence on resale prices.\n\n**Proximity to Preschool (PROX_PRESCHOOL)**\n\nStandard errors are moderate across most regions, with slightly higher values in fringe areas. T-values vary between positive and negative clusters, revealing that preschool proximity affects prices differently depending on neighbourhood context.\n\n**Proximity to Hawker Centre (PROX_HAWKER)**\n\nStandard errors are low in areas with dense hawker distributions, suggesting stable coefficient estimation. T-values are strongly negative in many towns, indicating that being farther from hawkers tends to reduce resale prices.\n\n**Proximity to Park (PROX_PARK)**\n\nStandard errors vary considerably, with more stability in park-rich regions like the East. T-values show mixed directionality, meaning the value of park proximity differs widely across Singapore.\n\n**Proximity to Supermarket (PROX_SUPERMARKET)**\n\nThis variable exhibits higher standard errors in less urbanised zones, showing weaker reliability. T-values are generally small and inconsistent, suggesting that supermarket access is not a major differentiator of resale prices.\n\n**Mid-Storey Indicator (STOREY_MID)**\n\nStandard errors are low and stable island-wide, indicating very reliable coefficient estimates. T-values are strongly positive everywhere, confirming that mid-storey flats consistently command a significant price premium.\n\n**Proximity to CHAS Clinic (PROX_CHASCLINIC)**\n\nStandard errors are moderate, with greater uncertainty in outer regions. T-values are mostly negative and significant in central and eastern towns, showing that households value closer access to subsidised clinics.\n\n**Proximity to Train Station (PROX_TRAINSTATION)**\n\nStandard errors are low in MRT-dense regions, reflecting strong data support. T-values are largely negative, indicating that proximity to train stations increases prices, though some areas show positive effects likely due to noise or structural factors.\\\n\n## Conclusion\n\nWe progressively transitioned from a simple linear regression to a multiple linear regression and finally to a Geographically Weighted Regression (GWR). This stepwise approach allowed us to increasingly capture the spatial structure embedded in the housing market. GWR, in particular, provided a much more suitable modelling framework by accounting for spatial heterogeneity and allowing relationships between predictors and resale prices to vary across Singapore. As a result, the final model better reflects the true spatial dynamics influencing HDB resale prices and produces a more robust and geographically sensitive prediction system.\n",
    "supporting": [
      "TakeHome_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}