---
title: "InClass_Ex09"
author: "Mohammad Farhan Ahsan"
format: html
---

## Getting Started

```{r}
pacman::p_load(SpatialAcc, sf, tidyverse, 
               tmap, ggstatsplot)
```

```{r}
#| output: false
eldercare <- st_read(dsn = "data/geospatial",
                     layer = "ELDERCARE") %>%
  st_transform(crs = 3414)
```

## Importing Data

### Geospatail data

```{r}
#| output: false
mpsz <- st_read(dsn = "data/geospatial",
                layer = "MP14_SUBZONE_NO_SEA_PL") %>%
  st_transform(crs = 3414)

hexagons <- st_read(dsn = "data/geospatial",
                    layer = "hexagons") %>%
  st_transform(crs = 3414)

eldercare <- st_read(dsn = "data/geospatial",
                     layer = "ELDERCARE") %>%
  st_transform(crs = 3414)
```

### OD Matrix

```{r}
ODMatrix <- read_csv("data/aspatial/OD_Matrix.csv", 
                     skip = 0)
```

## Data cleaning and Updating Attributes

### Supply

```{r}
eldercare <- eldercare %>%
  select(fid, ADDRESSPOS) %>%
  mutate(capacity = 100)
```

### Demand

```{r}
hexagons <- hexagons %>%
  select(fid) %>%
  mutate(demand = 100)
```

### OD Matrix

```{r}
distmat <- ODMatrix %>%
  select(origin_id, destination_id, total_cost) %>%
  spread(destination_id, total_cost)%>%
  select(c(-c('origin_id')))
```

```{r}
distmat_km <- as.matrix(distmat/1000)
```

```{r}
acc_Hansen <- data.frame(ac(hexagons$demand,
                            eldercare$capacity,
                            distmat_km, 
                            #d0 = 50,
                            power = 0.5, 
                            family = "Hansen"))
```

### Tidy the output

```{r}
colnames(acc_Hansen) <- "accHansen"

acc_Hansen <- as_tibble(acc_Hansen)

hexagon_Hansen <- bind_cols(hexagons, acc_Hansen)
```

## Hansen

```{r}
acc_Hansen <- data.frame(ac(hexagons$demand,
                            eldercare$capacity,
                            distmat_km, 
                            #d0 = 50,
                            power = 0.5, 
                            family = "Hansen"))

colnames(acc_Hansen) <- "accHansen"
acc_Hansen <- as_tibble(acc_Hansen)
hexagon_Hansen <- bind_cols(hexagons, acc_Hansen)
```

```{r}


# 0.5
acc_Hansen_0.5 <- data.frame(ac(hexagons$demand,
                               eldercare$capacity,
                               distmat_km, 
                               power = 0.5, 
                               family = "Hansen"))
colnames(acc_Hansen_0.5) <- "accHansen_0.5"
acc_Hansen_0.5 <- as_tibble(acc_Hansen_0.5)
hexagon_Hansen_0.5 <- bind_cols(hexagons, acc_Hansen_0.5)


# 1.0
acc_Hansen_1 <- data.frame(ac(hexagons$demand,
                              eldercare$capacity,
                              distmat_km, 
                              power = 1, 
                              family = "Hansen"))
colnames(acc_Hansen_1) <- "accHansen_1"
acc_Hansen_1 <- as_tibble(acc_Hansen_1)
hexagon_Hansen_1 <- bind_cols(hexagons, acc_Hansen_1)


# 1.5
acc_Hansen_1.5 <- data.frame(ac(hexagons$demand,
                                eldercare$capacity,
                                distmat_km, 
                                power = 1.5, 
                                family = "Hansen"))
colnames(acc_Hansen_1.5) <- "accHansen_1.5"
acc_Hansen_1.5 <- as_tibble(acc_Hansen_1.5)
hexagon_Hansen_1.5 <- bind_cols(hexagons, acc_Hansen_1.5)


# 2.0
acc_Hansen_2 <- data.frame(ac(hexagons$demand,
                              eldercare$capacity,
                              distmat_km, 
                              power = 2, 
                              family = "Hansen"))
colnames(acc_Hansen_2) <- "accHansen_2"
acc_Hansen_2 <- as_tibble(acc_Hansen_2)
hexagon_Hansen_2 <- bind_cols(hexagons, acc_Hansen_2)


# 2.5
acc_Hansen_2.5 <- data.frame(ac(hexagons$demand,
                                eldercare$capacity,
                                distmat_km, 
                                power = 2.5, 
                                family = "Hansen"))
colnames(acc_Hansen_2.5) <- "accHansen_2.5"
acc_Hansen_2.5 <- as_tibble(acc_Hansen_2.5)
hexagon_Hansen_2.5 <- bind_cols(hexagons, acc_Hansen_2.5)



```

### Visualising Accessibility

```{r}
mapex <- st_bbox(hexagons)
tmap_mode("plot")

p05 <- tm_shape(hexagon_Hansen_0.5, bbox = mapex) + 
  tm_polygons(fill = "accHansen_0.5",
              fill.scale = tm_scale_intervals(style="quantile", n=10, values="brewer.blues")) +
  tm_shape(eldercare) + tm_dots(size=0.3, fill="red", col="black") +
  tm_title("Power = 0.5") + tm_layout(frame=TRUE) +
  tm_compass(type="8star", size=2) + tm_scalebar(position=c("right","bottom")) +
  tm_grid(alpha=0.2)
p05
```

```{r}
p1 <- tm_shape(hexagon_Hansen_1, bbox = mapex) + 
  tm_polygons(fill = "accHansen_1",
              fill.scale = tm_scale_intervals(style="quantile", n=10, values="brewer.blues")) +
  tm_shape(eldercare) + tm_dots(size=0.3, fill="red", col="black") +
  tm_title("Power = 1.0") + tm_layout(frame=TRUE) +
  tm_compass(type="8star", size=2) + tm_scalebar(position=c("right","bottom")) +
  tm_grid(alpha=0.2)
p1
```

```{r}
p15 <- tm_shape(hexagon_Hansen_1.5, bbox = mapex) + 
  tm_polygons(fill = "accHansen_1.5",
              fill.scale = tm_scale_intervals(style="quantile", n=10, values="brewer.blues")) +
  tm_shape(eldercare) + tm_dots(size=0.3, fill="red", col="black") +
  tm_title("Power = 1.5") + tm_layout(frame=TRUE) +
  tm_compass(type="8star", size=2) + tm_scalebar(position=c("right","bottom")) +
  tm_grid(alpha=0.2)
p15
```

```{r}
p2 <- tm_shape(hexagon_Hansen_2, bbox = mapex) + 
  tm_polygons(fill = "accHansen_2",
              fill.scale = tm_scale_intervals(style="quantile", n=10, values="brewer.blues")) +
  tm_shape(eldercare) + tm_dots(size=0.3, fill="red", col="black") +
  tm_title("Power = 2.0") + tm_layout(frame=TRUE) +
  tm_compass(type="8star", size=2) + tm_scalebar(position=c("right","bottom")) +
  tm_grid(alpha=0.2)
p2
```

```{r}
p25 <- tm_shape(hexagon_Hansen_2.5, bbox = mapex) + 
  tm_polygons(fill = "accHansen_2.5",
              fill.scale = tm_scale_intervals(style="quantile", n=10, values="brewer.blues")) +
  tm_shape(eldercare) + tm_dots(size=0.3, fill="red", col="black") +
  tm_title("Power = 2.5") + tm_layout(frame=TRUE) +
  tm_compass(type="8star", size=2) + tm_scalebar(position=c("right","bottom")) +
  tm_grid(alpha=0.2)
  
p25
```
